<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageId>Moquestra.TypeIds</PackageId>
    <Description>A library for bidirectional mapping between types and integer IDs.</Description>
    <PackageTags>typeid;type-id;type-mapping;dispatch</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Moquestra.TypeIds.Tests, PublicKey=002400000480000014010000060200000024000052534131000800000100010049cd0298ffce18e00d1d6114b4e2e26810de05a3e25013deed6b3ded293b8197d531ad959f628e73f111aaa69fd3aedd503906baab861627fd88918f1b8c5b040d6c904bf62a39d0ade1e78faa2206a02e80797c301a89a46b7d9dedce0b5b4fdaaeec710f90e60868ca672ec2058809f5133d6d04ee4d5a5c75d4ee0de35cec71253c3597ed9da812ba9ab15d2286966dd000e2dd4d5dfc6b1a841ee0347a49222f1e68f7e871eddca67af242cb49c8a68cc484c65d1c016417d13359e078feef39e55155e7bb5da2ff8bdafcc7850ef19ae8e5a3d55b8e22518c21d4635f129d4fe9223c54355b18dbe64705bc459e64494d80e27eb1a793024a5caba31c9d" />
  </ItemGroup>

</Project>
